module Directory
(Var "createDirectory",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "doesDirectoryExist",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "doesFileExist",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "getCurrentDirectory",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "getDirectoryContents",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "getModificationTime",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "getPermissions",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "removeDirectory",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "removeFile",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "renameDirectory",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "renameFile",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "setCurrentDirectory",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "setPermissions",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "Permissions" "Permissions",Value {args = 4, fixity = Def, priority = 9, letBound = True, traced = False})
(Field "Permissions" "executable",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Field "Permissions" "readable",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Field "Permissions" "searchable",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Field "Permissions" "writable",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(TypeClass "Permissions",TyCls (Ty ["Permissions"] ["readable","writable","executable","searchable"]))
