module IO
(Var "appendFile",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "bracket",Value {args = 3, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "bracket_",Value {args = 3, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "catch",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "getChar",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "getContents",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "getLine",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hClose",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hFileSize",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hFlush",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hGetBuffering",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hGetChar",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hGetContents",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hGetLine",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hGetPosn",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hIsClosed",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hIsEOF",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hIsOpen",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hIsReadable",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hIsSeekable",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hIsWritable",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hLookAhead",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hPrint",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hPutChar",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hPutStr",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hPutStrLn",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hReady",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hSeek",Value {args = 3, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hSetBuffering",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hSetPosn",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "hWaitForInput",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "interact",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "ioError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "ioeGetErrorString",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "ioeGetFileName",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "ioeGetHandle",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isAlreadyExistsError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isAlreadyInUseError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isDoesNotExistError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isEOF",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isEOFError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isFullError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isIllegalOperation",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isPermissionError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isUserError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "openFile",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "print",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "putChar",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "putStr",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "putStrLn",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "readFile",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "readIO",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "readLn",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "stderr",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "stdin",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "stdout",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "try",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "userError",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "writeFile",Value {args = 2, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "BufferMode" "BlockBuffering",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "BufferMode" "LineBuffering",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "BufferMode" "NoBuffering",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "IOMode" "AppendMode",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "IOMode" "ReadMode",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "IOMode" "ReadWriteMode",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "IOMode" "WriteMode",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "SeekMode" "AbsoluteSeek",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "SeekMode" "RelativeSeek",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Con Data "SeekMode" "SeekFromEnd",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(TypeClass "BufferMode",TyCls (Ty ["NoBuffering","LineBuffering","BlockBuffering"] []))
(TypeClass "FilePath",TyCls (Syn 0 THelper))
(TypeClass "Handle",TyCls (Ty [] []))
(TypeClass "HandlePosn",TyCls (Ty [] []))
(TypeClass "IO",TyCls (Ty [] []))
(TypeClass "IOError",TyCls (Ty [] []))
(TypeClass "IOMode",TyCls (Ty ["ReadMode","WriteMode","AppendMode","ReadWriteMode"] []))
(TypeClass "SeekMode",TyCls (Ty ["AbsoluteSeek","RelativeSeek","SeekFromEnd"] []))
