module TPreludeBuiltinTypes
(TypeClass "IO", TyCls (Ty [] []))
(TypeClass "IOError", TyCls (Ty [] []))
(TypeClass "Double", TyCls (Ty [] []))
(TypeClass "Float", TyCls (Ty [] []))
(TypeClass "Integer", TyCls (Ty [] []))
(TypeClass "Int", TyCls (Ty [] []))
(TypeClass "Char", TyCls (Ty [] []))
(TypeClass "String", TyCls (Syn 0 THelper))
(TypeClass "Bool", TyCls (Ty ["False","True"] []))
(Con Data "Bool" "False",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Bool" "True",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
(Var "error",Value{args=1,fixity=Def,priority=9,letBound=True,traced=False})
(Var "undefined",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
