module TPreludeBuiltinTypes
(TypeClass "IO", TyCls (Ty [] []))
(TypeClass "IOError", TyCls (Ty [] []))
(TypeClass "Double", TyCls (Ty [] []))
(TypeClass "Float", TyCls (Ty [] []))
(TypeClass "Integer", TyCls (Ty [] []))
(TypeClass "Int", TyCls (Ty [] []))
(TypeClass "Char", TyCls (Ty [] []))
(TypeClass "->", TyCls (Ty [] []))
(TypeClass "String", TyCls (Ty [] []))
(TypeClass "[]", TyCls (Ty ["[]",":"] []))
(TypeClass "Bool", TyCls (Ty ["False","True"] []))
(TypeClass "()", TyCls (Ty ["()"] []))
(TypeClass "Prelude.2", TyCls (Ty ["Prelude.2"] []))
(TypeClass "Prelude.3", TyCls (Ty ["Prelude.3"] []))
(TypeClass "Prelude.4", TyCls (Ty ["Prelude.4"] []))
(TypeClass "Prelude.5", TyCls (Ty ["Prelude.5"] []))
(TypeClass "Prelude.6", TyCls (Ty ["Prelude.6"] []))
(TypeClass "Prelude.7", TyCls (Ty ["Prelude.7"] []))
(TypeClass "Prelude.8", TyCls (Ty ["Prelude.8"] []))
(TypeClass "Prelude.9", TyCls (Ty ["Prelude.9"] []))
(TypeClass "Prelude.10", TyCls (Ty ["Prelude.10"] []))
(TypeClass "Prelude.11", TyCls (Ty ["Prelude.11"] []))
(TypeClass "Prelude.12", TyCls (Ty ["Prelude.12"] []))
(TypeClass "Prelude.13", TyCls (Ty ["Prelude.13"] []))
(TypeClass "Prelude.14", TyCls (Ty ["Prelude.14"] []))
(TypeClass "Prelude.15", TyCls (Ty ["Prelude.15"] []))
(Con Data "[]" ":",Value{args=2,fixity=R,priority=5,letBound=True,traced=False})
(Con Data "[]" "[]",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Bool" "False",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Bool" "True",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "()" "()",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.2" "Prelude.2",Value{args=2,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.3" "Prelude.3",Value{args=3,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.4" "Prelude.4",Value{args=4,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.5" "Prelude.5",Value{args=5,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.6" "Prelude.6",Value{args=6,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.7" "Prelude.7",Value{args=7,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.8" "Prelude.8",Value{args=8,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.9" "Prelude.9",Value{args=9,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.10" "Prelude.10",Value{args=10,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.11" "Prelude.11",Value{args=11,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.12" "Prelude.12",Value{args=12,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.13" "Prelude.13",Value{args=13,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.14" "Prelude.14",Value{args=14,fixity=Def,priority=9,letBound=True,traced=False})
(Con Data "Prelude.15" "Prelude.15",Value{args=15,fixity=Def,priority=9,letBound=True,traced=False})
(Var "error",Value{args=1,fixity=Def,priority=9,letBound=True,traced=False})
(Var "undefined",Value{args=0,fixity=Def,priority=9,letBound=True,traced=False})
