module Char
(Var "chr",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "digitToInt",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "intToDigit",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isAlpha",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isAlphaNum",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isAscii",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isControl",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isDigit",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isHexDigit",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isLatin1",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isLower",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isOctDigit",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isPrint",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isSpace",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "isUpper",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "lexLitChar",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "ord",Value {args = 0, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "readLitChar",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "showLitChar",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "toLower",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(Var "toUpper",Value {args = 1, fixity = Def, priority = 9, letBound = True, traced = False})
(TypeClass "Char",TyCls (Ty [] []))
(TypeClass "String",TyCls (Ty [] []))
